### ISSUE TITLE
Access denied due to invalid subscription key or wrong API endpoint

### ISSUE THREAD

**Issue by DieterLudwig** [DelphiABall/Azure-Cognitive-Services#6]
Hello, 
I always get an 401 Access denied error with the given Example.
Fiddler shows, that _subscription-key_ is sent in the Body, not Header.

I am using CE 10.4

Greetings
Dieter Ludwig

**Comment by DelphiABall** [comment]
Have you set up your own subscription key on the services?

**Comment by DieterLudwig** [comment]
Thank you for fast! reply.
Yes, I set my own Key.
He works in other programs.

**Comment by DieterLudwig** [comment]
I solved it, and now it works fine.

Here my changes:
**Azure.API3.Connection.pas**

change all _subscription-key_ to _ocp-apim-subscription-key_

In TAzureToken.Create
add:
  _RRP.Kind := TRESTRequestParameterKind.pkHTTPHEADER;
  RRP.Options := [TRESTRequestParameterOption.poDoNotEncode];_

**Comment by DelphiABall** [comment]
That will work but isn't the way this library is implemented. It sounds like you didn't create the instance of the Authorisation object and assign it to the object being called. For added security, this uses the other method of authentication that gets an access token which is then shared. Please have a look at the sample app.
